version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres  
      POSTGRES_PASSWORD: root 
      POSTGRES_DB: answers_ai  
    ports:
      - "5432:5432"

  app:
    build: .
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres  
      POSTGRES_PASSWORD: root  
      POSTGRES_DB: answers_ai  q
    ports:
      - "5000:5000"

